// The adapter-cloudflare build output — only exists after `vite build`, which `bun run check`
// and `bun run build` both run first. `checkJs: false` in tsconfig.json keeps TypeScript from
// walking this untyped, generated file's own internals; an ambient `declare module` for it was
// tried instead but doesn't work, since TypeScript never applies an ambient declaration to a
// relative import path — it always resolves those against the real file on disk.
import svelteKit from '../.svelte-kit/cloudflare/_worker.js';
import { route } from './worker/routing';
export { ProjectRoom } from './worker/project-room';

// `Env` here is the global type from worker-configuration.d.ts (generated by `wrangler types`
// from wrangler.jsonc), not the Env from project-room.ts: it includes ASSETS, which the
// Durable Object's narrower Env doesn't have but which is needed to delegate to SvelteKit.

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext) {
		return route(request, env, ctx, (req, e, c) => svelteKit.fetch(req, e, c));
	}
} satisfies ExportedHandler<Env>;
