#!/usr/bin/env bun
// One-command deploy for sourcebeam: login -> KV namespace -> generated config -> build ->
// deploy -> seed a host token. Run with --dry-run to see the plan without side effects.
import { randomBytes } from "node:crypto";
import { $, file, spawn, write } from "bun";
import { amber, blue, bold, dim, link, navy } from "./lib/colors";
import {
	ensureLoggedIn,
	fail,
	findNamespace,
	listNamespaces,
	namespaceTitleFor,
	resolveWorkerName,
	ROOT,
	WEB_DIR,
	WRANGLER,
	WRANGLER_ENV,
	wrangler,
} from "./lib/cloudflare";

// file:// links into the user's own checkout — see scripts/lib/colors.ts's `link` doc comment
// for why this beats a github.com URL (no branch/network/public-repo dependency).
const fileLink = (relPath: string, text = relPath) => link(text, `file://${ROOT}${relPath}`);

const dryRun = process.argv.includes("--dry-run");

function log(step: string, msg: string) {
	console.log(`[${step}] ${msg}`);
}

// --- 1. Config from environment -------------------------------------------------------------

const workerName = resolveWorkerName();
log("config", `worker name: ${workerName}`);

if (dryRun) {
	// Genuinely side-effect-free: this used to still run ensureLoggedIn() (which can pop a
	// browser login prompt), listNamespaces() (a real Cloudflare API call) and write
	// wrangler.generated.jsonc to disk before reaching this check — none of that is "no side
	// effects". Bail out immediately after the one thing that's pure local computation.
	const namespaceTitle = namespaceTitleFor(workerName);
	log("auth", "would check Cloudflare login, prompting via the browser if needed (skipped: --dry-run)");
	log("kv", `would look for an existing KV namespace named "${namespaceTitle}", creating it if missing (skipped: --dry-run)`);
	log("config", `would write ${WEB_DIR}/wrangler.generated.jsonc (skipped: --dry-run)`);
	log("build", "would run: bun run --cwd apps/web build (skipped: --dry-run)");
	log("deploy", "would run: wrangler deploy -c wrangler.generated.jsonc (skipped: --dry-run)");
	log("token", "would check apps/web KV for existing host tokens and seed one if none exist (skipped: --dry-run)");
	log("summary", "dry run complete — no login prompt, network requests, or local writes were performed.");
	process.exit(0);
}

// --- 2. Cloudflare login -----------------------------------------------------------------

log("auth", "checking Cloudflare login...");
await ensureLoggedIn();
log("auth", "logged in to Cloudflare.");

// --- 3. KV namespace ------------------------------------------------------------------------

const namespaceTitle = namespaceTitleFor(workerName);
log("kv", "looking for an existing KV namespace...");
let namespaces = await listNamespaces();
let ns = findNamespace(namespaces, workerName);

if (ns) {
	log("kv", `found existing namespace "${ns.title}" (${ns.id}) — reusing it.`);
} else {
	log("kv", `no existing namespace — creating "${namespaceTitle}"...`);
	const created = await wrangler(["kv", "namespace", "create", namespaceTitle]);
	if (created.exitCode !== 0) fail(`\`wrangler kv namespace create\` failed:\n${created.stderr}`);
	// Parsing `create`'s own output isn't reliable across wrangler versions — re-list instead.
	namespaces = await listNamespaces();
	const createdNs = namespaces.find((n) => n.title === namespaceTitle);
	if (!createdNs) fail(`created namespace "${namespaceTitle}" but couldn't find it again via \`wrangler kv namespace list\`.`);
	ns = createdNs;
	log("kv", `created namespace "${ns.title}" (${ns.id}).`);
}

// --- 4. Generate wrangler.generated.jsonc ------------------------------------------------

const templatePath = `${WEB_DIR}/wrangler.jsonc`;
const generatedPath = `${WEB_DIR}/wrangler.generated.jsonc`;
const template = await file(templatePath).text();

let generated = template.replace(/"name":\s*"sourcebeam"/, `"name": "${workerName}"`);
if (!generated.includes(`"name": "${workerName}"`)) {
	fail(`could not find the "name" field (expected literal "sourcebeam") in ${templatePath}.`);
}

const withoutId = generated;
generated = generated.replace(/"id":\s*"<your-kv-namespace-id>"/, `"id": "${ns.id}"`);
if (generated === withoutId) {
	fail(`could not find the "<your-kv-namespace-id>" placeholder in ${templatePath}.`);
}

generated =
	`// GENERATED by \`bun run deploy\` — do not edit, this file is overwritten on every run.\n` +
	`// Edit apps/web/wrangler.jsonc instead and re-run \`bun run deploy\`.\n` +
	generated;

await write(generatedPath, generated);
log("config", `wrote ${generatedPath} (name=${workerName}, kv id=${ns.id}).`);

// --- 5. Build ---------------------------------------------------------------------------

log("build", "building apps/web...");
const build = await $`bun run --cwd ${WEB_DIR} build`.nothrow();
if (build.exitCode !== 0) fail("build failed — see output above.");
log("build", "build complete.");

// --- 6. Deploy --------------------------------------------------------------------------

log("deploy", "deploying...");
const deployProc = spawn([...WRANGLER, "deploy", "-c", "wrangler.generated.jsonc"], {
	cwd: WEB_DIR,
	env: WRANGLER_ENV,
	stdout: "pipe",
	stderr: "pipe",
});
const [deployStdout, deployStderr, deployExit] = await Promise.all([
	new Response(deployProc.stdout).text(),
	new Response(deployProc.stderr).text(),
	deployProc.exited,
]);
process.stdout.write(deployStdout);
process.stderr.write(deployStderr);
if (deployExit !== 0) fail("`wrangler deploy` failed — see output above.");

const urlMatch = (deployStdout + deployStderr).match(/https:\/\/[a-z0-9-]+\.[a-z0-9-]+\.workers\.dev/);
const workerUrl = urlMatch?.[0];
if (!workerUrl) {
	log("deploy", "deploy succeeded but couldn't find the workers.dev URL in wrangler's output.");
} else {
	log("deploy", `deployed to ${workerUrl}`);
}

// --- 7. Host token --------------------------------------------------------------------------

log("token", "checking for existing host tokens...");
const keysRes = await wrangler(["kv", "key", "list", "--namespace-id", ns.id, "--remote"]);
if (keysRes.exitCode !== 0) fail(`\`wrangler kv key list\` failed:\n${keysRes.stderr}`);
let keys: { name: string }[];
try {
	keys = JSON.parse(keysRes.stdout);
} catch {
	fail(`could not parse \`wrangler kv key list\` output as JSON:\n${keysRes.stdout}`);
}

let newToken: string | undefined;
if (keys.length > 0) {
	log("token", `${keys.length} host token(s) already exist — leaving them as-is.`);
} else {
	newToken = randomBytes(24).toString("hex");
	const put = await wrangler(["kv", "key", "put", "--namespace-id", ns.id, "--remote", newToken, '{"label":"owner"}']);
	if (put.exitCode !== 0) fail(`\`wrangler kv key put\` failed:\n${put.stderr}`);
	log("token", "seeded a new host token.");
}

// --- 8. Summary -------------------------------------------------------------------------

const wsUrl = workerUrl ? `wss://${new URL(workerUrl).host}` : "wss://<your-worker>.<subdomain>.workers.dev";

console.log(`\n${bold(amber("=== Deploy complete ==="))}`);
if (workerUrl) console.log(`${dim("Worker URL:")} ${blue(bold(workerUrl))}`);

console.log(`\n${bold("Next steps:")}`);
console.log(`  ${amber("1.")} Install the host extension — full setup walkthrough in each README:`);
console.log(`     ${navy("-")} VS Code: ${blue(fileLink("extensions/vscode/README.md"))}`);
console.log(`     ${navy("-")} JetBrains IDEs: ${blue(fileLink("extensions/jetbrains/README.md"))}`);
console.log(`  ${amber("2.")} Point it at this worker — set the ${bold("server URL")} to ${blue(wsUrl)}`);
console.log(`     ${dim("(VS Code: the sourcebeam.serverUrl setting. JetBrains: Settings | Tools | Sourcebeam.)")}`);
console.log(`  ${amber("3.")} Set a ${bold("project id")} ${dim("(lowercase letters, digits, hyphens, underscores)")} next to the server URL.`);
console.log(`  ${amber("4.")} Get a ${bold("host token")} — a separate secret from the project id, proving an editor`);
console.log(`     is allowed to broadcast at all. It is ${bold("not")} generated by the extension itself:`);
if (newToken) {
	console.log(`     ${dim("shown below, once — copy it now, it is not stored anywhere else.")}`);
} else {
	console.log(`     ${dim("this worker already has token(s); mint yourself one:")}`);
	console.log(`       ${blue("bun run token new [name]")}`);
	console.log(
		`     ${dim("(list, rename, rotate, revoke — see")} ${blue(fileLink("docs/self-hosting.md#managing-host-tokens"))}${dim(")")}`,
	);
}
console.log(`  ${amber("5.")} In the extension: run ${bold('"Set Host Token"')} (paste it in), then ${bold('"Start Broadcasting"')}.`);

if (newToken) {
	console.log(`\n${bold("Host token")} ${dim("(shown once — it is not stored anywhere else, save it now):")}\n${bold(amber(newToken))}`);
}
